### ISSUE TITLE
What does this project use for?

### ISSUE THREAD

**Issue by monanahe** [johndpope/sims4-ai-engine#1]
Is it for control and change sims4 AI settings?

**Comment by johndpope** [comment]
Short answer - It’s just for reference purposes. I couldn’t get it to run. But it’s from the game.

I was researching building out code that could keep track of emotions in virtualized world / without necessarily any 3D component. Characters that interact would shape the emotion scores.  There’s a flash game called prom night that captured this spirit. I’ll add link if I can dig it up.
